{% set version = "0.3.2" %}
{% set sha256 = "5ef2110aff82e3844f98b395301f3a56074d8388fec3e92a2c0a08e93da2df21" %}

package:
  name: reducer
  version: {{ version }}

source:
  fn: reducer-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/reducer/reducer-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - py2_patch.diff  # [py2k]
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - reducer = reducer:main
    #
    # Would create an entry point called reducer that calls reducer.main()

    - reducer = reducer:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - astropy >=1.2
    - numpy
    - scipy
    - scikit-image
    - ipywidgets 5.*
    - msumastro >=0.9
    - ccdproc >=1
    - matplotlib
    - dask

test:
  # Python imports
  imports:
    - reducer

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - reducer --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - astropy >=1.0
    - ccdproc >=1
    - dask
    - ipywidgets >=4.0.1,<5
    - matplotlib
    - msumastro >=0.9
    - numpy
    - pytest >1.4
    - scikit-image
    - scipy
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://reducer.readthedocs.org
  license: BSD 3-part
  summary: 'Process FITS files'
